### PR TITLE
auto restore functionality

### PR DESCRIPTION
**Pull request by curiousercreative**
# Description
Allows a user to opt-in for having a session automatically restored upon login. User can also manually specify which session name should be auto restored.

## Issues Resolved
Partially addresses: https://github.com/johannesjo/gnome-shell-extension-window-session-manager/issues/17

## Check List

- [x] New functionality includes testing.
    I manually tested...
- [ ] New functionality has been documented in the README if applicable.
    I haven't updated yet as I hope to get the auto saving working before this is merged.

### CODE REVIEW

**Comment by johannesjo** [comment]
Hey there! Thanks for making this work! Would be great if another person would volunteer for testing this!! Seems to work nicely so far on my machine!

**Comment by curiousercreative** [comment]
I noticed last night that the menu bar icon disappeared after resuming from suspend (or perhaps lock screen), so I'll need to look into that.

**Comment by johannesjo** [comment]
@curiousercreative I didn't encounter any issues with the new functionality. Also: While I didn't think that I would need the feature, I am now using it every day and I am pretty happy about it. Thank you very much again!

**Comment by curiousercreative** [comment]
Yeah, my new System76 laptop doesn't survive long while suspended, so I find myself having to shut down while in the middle of something quite often. Glad you're not noticing any problems, but I continue to have the shell icon disappear on me!

**Comment by johannesjo** [comment]
@curiousercreative I hope it's alright if I am merging this!

**Comment by curiousercreative** [comment]
> @curiousercreative I hope it's alright if I am merging this!

Of course!

**Pull request merged**
